# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.
class_name RegistryKeys

class Projectiles:
	const SENSOR_PROJECTILE: StringName = &"sensor_projectile"
	const SOLID_PROJECTILE: StringName = &"solid_projectile"
	const LIST: PackedStringArray = [SENSOR_PROJECTILE,SOLID_PROJECTILE]

class Skills:
	const DASH: StringName = &"dash"
	const SHOOT_SENSOR: StringName = &"shoot_sensor"
	const SHOOT_SOLID: StringName = &"shoot_solid"
	const SPRINT: StringName = &"sprint"
	const TELEKINESIS: StringName = &"telekinesis"
	const LIST: PackedStringArray = [DASH,SHOOT_SENSOR,SHOOT_SOLID,SPRINT,TELEKINESIS]

class Enemies:
	const BASE_DUMMY: StringName = &"base_dummy"
	const LIST: PackedStringArray = [BASE_DUMMY]

class Waves:
	const TRAINING_WAVE: StringName = &"training_wave"
	const LIST: PackedStringArray = [TRAINING_WAVE]

class VFX:
	const BUBBLE_VFX: StringName = &"bubble_vfx"
	const LIST: PackedStringArray = [BUBBLE_VFX]

