# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.
class_name RegistryKeys

class Projectiles:
	const SENSOR_PROJECTILE: StringName = &"sensor_projectile"
	const SOLID_PROJECTILE: StringName = &"solid_projectile"
	const LIST: PackedStringArray = [SENSOR_PROJECTILE,SOLID_PROJECTILE]

class Skills:
	const DASH: StringName = &"dash"
	const SHOOT_SENSOR: StringName = &"shoot_sensor"
	const SHOOT_SOLID: StringName = &"shoot_solid"
	const SPRINT: StringName = &"sprint"
	const TELEKINESIS: StringName = &"telekinesis"
	const LIST: PackedStringArray = [DASH,SHOOT_SENSOR,SHOOT_SOLID,SPRINT,TELEKINESIS]

class Enemies:
	const DUMMY: StringName = &"dummy"
	const WANDERER: StringName = &"wanderer"
	const LIST: PackedStringArray = [DUMMY,WANDERER]

class Waves:
	const DUMMY_WAVE_X12: StringName = &"dummy_wave_x12"
	const DUMMY_WAVE_X4: StringName = &"dummy_wave_x4"
	const WANDERER_WAVE: StringName = &"wanderer_wave"
	const LIST: PackedStringArray = [DUMMY_WAVE_X12,DUMMY_WAVE_X4,WANDERER_WAVE]

class VFX:
	const BUBBLE_VFX: StringName = &"bubble_vfx"
	const LIST: PackedStringArray = [BUBBLE_VFX]

