@tool
extends EditorPlugin

const GENERATED_FILE_PATH = RegistryConfig.Paths.REGISTRY_KEYS
const CATALOG_MANIFEST = RegistryConfig.CATALOG_MANIFEST

func _enter_tree() -> void:
	var file_system: EditorFileSystem = EditorInterface.get_resource_filesystem()
	
	file_system.resources_reimported.connect(_on_resources_reimported)
	file_system.filesystem_changed.connect(_on_filesystem_changed)
	
	print("RegistryKeyGenerator: Plugin activated")

func _exit_tree() -> void:
	var file_system: EditorFileSystem = EditorInterface.get_resource_filesystem()
	
	if file_system:
		if file_system.resources_reimported.is_connected(_on_resources_reimported):
			file_system.resources_reimported.disconnect(_on_resources_reimported)
			
		if file_system.filesystem_changed.is_connected(_on_filesystem_changed):
			file_system.filesystem_changed.disconnect(_on_filesystem_changed)
			
	print("RegistryKeyGenerator: Plugin deactivated")

func _on_resources_reimported(paths: PackedStringArray) -> void:
	for path in paths:
		for catalog_name in CATALOG_MANIFEST:
			if path.begins_with(CATALOG_MANIFEST[catalog_name].path):
				_regenerate_all_keys()
				return

func _on_filesystem_changed() -> void:
	_regenerate_all_keys()

func _regenerate_all_keys() -> void:
	print("REGENERATE ALL KEYS")
	
	var code: String = "# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.\n"
	code += "class_name RegistryKeys\n\n"
	
	for catalog_name in CATALOG_MANIFEST:
		var catalog_config := CATALOG_MANIFEST[catalog_name]
		
		code += "class %s:\n" % catalog_name
		var const_names: Array[String] = []
		
		code += _scan_dir(catalog_config.path, catalog_config.target_ext, const_names)
		
		code += "\tconst LIST: PackedStringArray = [%s]\n\n" % ",".join(const_names)
	
	var existing_content: String = ""
	if FileAccess.file_exists(GENERATED_FILE_PATH):
		existing_content = FileAccess.get_file_as_string(GENERATED_FILE_PATH)
	
	if code != existing_content:
		var file: FileAccess = FileAccess.open(GENERATED_FILE_PATH, FileAccess.WRITE)
		
		if file:
			file.store_string(code)
			file.close()
			
			EditorInterface.get_resource_filesystem().reimport_files([GENERATED_FILE_PATH])

func _scan_dir(dir_path: String, target_ext: String, const_names: Array[String]) -> String:
	var files: PackedStringArray = ResourceLoader.list_directory(dir_path)
	var code: String = ""
	
	for file_name in files:
		if file_name.ends_with("/"):
			code += _scan_dir(dir_path.path_join(file_name.trim_suffix("/")), target_ext, const_names)
		elif file_name.ends_with(target_ext):
			var key_name: String = file_name.get_basename()
			var constant_name: String = key_name.to_upper().replace(" ", "_")
			
			code += "\tconst %s: StringName = &\"%s\"\n" % [constant_name, key_name]
			const_names.append(constant_name)
	
	return code
